# Generated by Django 4.1.4 on 2022-12-17 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Forex',
        ),
    ]
